apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev-redmine
generatorOptions:
  disableNameSuffixHash: true
namePrefix: dev-redmine-
nameSuffix: "-001"
secretGenerator:
- name: kustomize-password
  files:
  - password=password.txt