apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: testing-redmine
generatorOptions:
  disableNameSuffixHash: true
namePrefix: testing-redmine-
nameSuffix: "-001"
secretGenerator:
- name: kustomize-password
  files:
  - password=password.txt