apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: redmine
resources:
  - ../../base
  - secret-avp.yaml
configMapGenerator:
- name: template-config
  literals:
  - MYSQL_DATABASE=redmine
  - MYSQL_USER=redmine
  - REDMINE_DB_MYSQL=backend-db01
  - REDMINE_DB_USERNAME=redmine
  - REDMINE_DB_DATABASE=redmine
  - REDMINE_PLUGINS_MIGRATE=true
transformers:
- transformer-labels.yaml
- transformer-suffixprefix.yaml
images:
  - name: frontend-app01
    newName: redmine
    newTag: "5.0.3"
  - name: backend-db01
    newName: mariadb
    newTag: "10.5"
replicas:
- name: frontend-app01
  count: 1
patches:
### storage ###
  - target:
      version: v1
      kind: PersistentVolumeClaim
      name: frontend-app01
    patch: |-
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: frontend-app01
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 3Gi
        storageClassName: longhorn
        volumeMode: Filesystem
  - target:
      version: v1
      kind: PersistentVolumeClaim
      name: frontend-app02
    patch: |-
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: frontend-app02
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: longhorn
        volumeMode: Filesystem
  - target:
      version: v1
      kind: PersistentVolumeClaim
      name: frontend-app03
    patch: |-
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: frontend-app03
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: longhorn
        volumeMode: Filesystem
  - target:
      version: v1
      kind: PersistentVolumeClaim
      name: backend-db01
    patch: |-
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: backend-db01
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: longhorn
        volumeMode: Filesystem
