apiVersion: v1
kind: Service
metadata:
  name: frontend-app01
spec:
  selector:
    app.kubernetes.io/name: redmine-app
    app.kubernetes.io/component: server
  ports:
  - port: 80
    targetPort: 3000
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frontend-app01
  labels:
    app.kubernetes.io/name: redmine-app
    app.kubernetes.io/component: server
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frontend-app02
  labels:
    app.kubernetes.io/name: redmine-app
    app.kubernetes.io/component: server
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frontend-app03
  labels:
    app.kubernetes.io/name: redmine-app
    app.kubernetes.io/component: server
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  storageClassName: longhorn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app01
  labels:
    app.kubernetes.io/name: redmine-app
    app.kubernetes.io/component: server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: redmine-app
      app.kubernetes.io/component: server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redmine-app
        app.kubernetes.io/component: server
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - redmine-app
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: frontend-app01
        image: frontend-app01
        imagePullPolicy: Always
        env:
        - name: REDMINE_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kustomize-password
              key: password  
        - name: REDMINE_DB_MYSQL
          valueFrom:
            configMapKeyRef:
              name: template-config
              key: REDMINE_DB_MYSQL
        - name: REDMINE_DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: template-config
              key: REDMINE_DB_DATABASE
        - name: REDMINE_DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: template-config
              key: REDMINE_DB_USERNAME
        - name: REDMINE_PLUGINS_MIGRATE
          valueFrom:
            configMapKeyRef:
              name: template-config
              key: REDMINE_PLUGINS_MIGRATE
        - name: TZ
          value: "Asia/Tokyo"
        resources:
          limits:
            memory: 512Mi
            cpu: "0.5"
          requests:
            memory: 512Mi
            cpu: "0.25"
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: frontend-app01
          mountPath: /usr/src/redmine/files
        - name: frontend-app02
          mountPath: /usr/src/redmine/plugins
        - name: frontend-app03
          mountPath: /usr/src/redmine/public/themes
      volumes:
      - name: frontend-app01
        persistentVolumeClaim:
          claimName: frontend-app01
      - name: frontend-app02
        persistentVolumeClaim:
          claimName: frontend-app02
      - name: frontend-app03
        persistentVolumeClaim:
          claimName: frontend-app03
