apiVersion: v1
kind: Service
metadata:
  name: backend-db01
  labels:
    app.kubernetes.io/name: redmine-db
    app.kubernetes.io/component: database
spec:
  selector:
    app.kubernetes.io/name: redmine-db
    app.kubernetes.io/component: database
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-db01
  labels:
    app.kubernetes.io/name: redmine-db
    app.kubernetes.io/component: database
spec:
  resources:
    requests:
      storage: 3Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-db01
  labels:
    app.kubernetes.io/name: redmine-db
    app.kubernetes.io/component: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redmine-db
      app.kubernetes.io/component: database
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redmine-db
        app.kubernetes.io/component: database
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.iio/name
                operator: In
                values:
                - redmine-db
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: backend-db01
        image: backend-db01
        imagePullPolicy: Always
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kustomize-password
              key: password     
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kustomize-password
              key: password 
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: template-config
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: template-config
              key: MYSQL_USER  
        resources:
          limits:
            memory: 512Mi
            cpu: "0.5"
          requests:
            memory: 512Mi
            cpu: "0.25"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: backend-db01
          mountPath: /var/lib/mysql
      volumes:
      - name: backend-db01
        persistentVolumeClaim:
          claimName: backend-db01
      